apiVersion: 1

datasources:
  - name: NetWatch-OpenSearch
    uid: netwatch-opensearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    isDefault: true
    jsonData:
      database: "netwatch-conn-*"
      flavor: opensearch
      version: "2.11.0"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
    editable: true

  - name: NetWatch-Prometheus
    uid: netwatch-prometheus
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    editable: true
